spring.datasource.url=jdbc:postgresql://localhost:5432/training-api-db
spring.datasource.username=root
spring.datasource.password=Pass1234

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true