spring.application.name=training-api

spring.datasource.url=jdbc:postgresql://localhost:5432/training-api-db
spring.datasource.username=root
spring.datasource.password=Pass1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true